name: watch_my_wallet
description: "A  new way to manage all your expenses"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.17.2
  flutter_bloc: ^9.1.1
  equatable: ^2.1.0
  provider: ^6.1.1
  google_nav_bar: ^5.0.7
  line_icons: ^2.0.3
  page_transition: ^2.2.2
  dropdown_button2: ^3.1.0
  intl: ^0.20.3
  fl_chart: ^0.71.0
  sqflite_sqlcipher: ^3.4.1
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
